<?php

use Illuminate\Database\Seeder;

class logoTypeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //ロゴのタイプ
        \DB::table('logo_types')->insert([
            [
                "type_parent_id"=>"1",
                "type_child_id"=>"1",
                "type_name"=>"カフェ・バー"
            ],
            [
                "type_parent_id"=>"1",
                "type_child_id"=>"2",
                "type_name"=>"料理・料理教室"
            ],
            [
                "type_parent_id"=>"1",
                "type_child_id"=>"3",
                "type_name"=>"レストラン"
            ],
            [
                "type_parent_id"=>"1",
                "type_child_id"=>"4",
                "type_name"=>"グルメ"
            ],
            [
                "type_parent_id"=>"1",
                "type_child_id"=>"5",
                "type_name"=>"スイーツ"
            ],
            [
                "type_parent_id"=>"2",
                "type_child_id"=>"1",
                "type_name"=>"美容院"
            ],
            [
                "type_parent_id"=>"2",
                "type_child_id"=>"2",
                "type_name"=>"コスメ"
            ],
            [
                "type_parent_id"=>"2",
                "type_child_id"=>"3",
                "type_name"=>"ネイル"
            ],
            [
                "type_parent_id"=>"2",
                "type_child_id"=>"4",
                "type_name"=>"ヨガ"
            ],
            [
                "type_parent_id"=>"2",
                "type_child_id"=>"5",
                "type_name"=>"エステ"
            ],
            [
                "type_parent_id"=>"3",
                "type_child_id"=>"1",
                "type_name"=>"サービス"
            ],
            [
                "type_parent_id"=>"3",
                "type_child_id"=>"2",
                "type_name"=>"SNS"
            ],
            [
                "type_parent_id"=>"3",
                "type_child_id"=>"3",
                "type_name"=>"インターネット"
            ],
            [
                "type_parent_id"=>"3",
                "type_child_id"=>"4",
                "type_name"=>"ロボット"
            ],
            [
                "type_parent_id"=>"3",
                "type_child_id"=>"5",
                "type_name"=>"パソコン"
            ],
            [
                "type_parent_id"=>"3",
                "type_child_id"=>"6",
                "type_name"=>"ビジネス"
            ],
            [
                "type_parent_id"=>"4",
                "type_child_id"=>"1",
                "type_name"=>"英語"
            ],
            [
                "type_parent_id"=>"4",
                "type_child_id"=>"2",
                "type_name"=>"学校・塾"
            ],
            [
                "type_parent_id"=>"4",
                "type_child_id"=>"3",
                "type_name"=>"習い事"
            ],
            [
                "type_parent_id"=>"4",
                "type_child_id"=>"4",
                "type_name"=>"留学"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"1",
                "type_name"=>"サッカー"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"2",
                "type_name"=>"野球"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"3",
                "type_name"=>"テニス"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"4",
                "type_name"=>"バレー"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"5",
                "type_name"=>"バスケットボール"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"6",
                "type_name"=>"柔道"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"7",
                "type_name"=>"ボクシング"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"8",
                "type_name"=>"ダンス"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"9",
                "type_name"=>"マラソン"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"10",
                "type_name"=>"ジム"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"1",
                "type_name"=>"ピアノ"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"2",
                "type_name"=>"バイオリン"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"3",
                "type_name"=>"ギター"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"4",
                "type_name"=>"バンド"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"5",
                "type_name"=>"和楽器"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"6",
                "type_name"=>"DJ"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"7",
                "type_name"=>"アイドル"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"1",
                "type_name"=>"犬"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"2",
                "type_name"=>"猫"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"3",
                "type_name"=>"魚"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"4",
                "type_name"=>"鳥"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"5",
                "type_name"=>"哺乳類"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"6",
                "type_name"=>"小動物"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"7",
                "type_name"=>"爬虫類"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"8",
                "type_name"=>"両生類"
            ],
            [
                "type_parent_id"=>"12",
                "type_child_id"=>"1",
                "type_name"=>"本"
            ],
            [
                "type_parent_id"=>"12",
                "type_child_id"=>"2",
                "type_name"=>"漫画"
            ],
            [
                "type_parent_id"=>"12",
                "type_child_id"=>"3",
                "type_name"=>"映画"
            ],
            [
                "type_parent_id"=>"12",
                "type_child_id"=>"4",
                "type_name"=>"アニメ"
            ],
            [
                "type_parent_id"=>"12",
                "type_child_id"=>"5",
                "type_name"=>"ゲーム"
            ],
            [
                "type_parent_id"=>"16",
                "type_child_id"=>"1",
                "type_name"=>"車"
            ],
            [
                "type_parent_id"=>"16",
                "type_child_id"=>"2",
                "type_name"=>"バイク"
            ],
            [
                "type_parent_id"=>"16",
                "type_child_id"=>"3",
                "type_name"=>"映画"
            ],
            [
                "type_parent_id"=>"16",
                "type_child_id"=>"4",
                "type_name"=>"船"
            ],
            [
                "type_parent_id"=>"16",
                "type_child_id"=>"5",
                "type_name"=>"飛行機"
            ],
            [
                "type_parent_id"=>"22",
                "type_child_id"=>"1",
                "type_name"=>"春"
            ],
            [
                "type_parent_id"=>"22",
                "type_child_id"=>"2",
                "type_name"=>"夏"
            ],
            [
                "type_parent_id"=>"22",
                "type_child_id"=>"3",
                "type_name"=>"秋"
            ],
            [
                "type_parent_id"=>"22",
                "type_child_id"=>"4",
                "type_name"=>"冬"
            ],
            [
                "type_parent_id"=>"1",
                "type_child_id"=>"0",
                "type_name"=>"飲食・グルメ"
            ],
            [
                "type_parent_id"=>"2",
                "type_child_id"=>"0",
                "type_name"=>"美容・セラピー"
            ],
            [
                "type_parent_id"=>"3",
                "type_child_id"=>"0",
                "type_name"=>"IT"
            ],
            [
                "type_parent_id"=>"4",
                "type_child_id"=>"0",
                "type_name"=>"教育"
            ],
            [
                "type_parent_id"=>"5",
                "type_child_id"=>"0",
                "type_name"=>"スポーツ"
            ],
            [
                "type_parent_id"=>"6",
                "type_child_id"=>"0",
                "type_name"=>"音楽"
            ],
            [
                "type_parent_id"=>"7",
                "type_child_id"=>"0",
                "type_name"=>"宿泊"
            ],
            [
                "type_parent_id"=>"8",
                "type_child_id"=>"0",
                "type_name"=>"動物"
            ],
            [
                "type_parent_id"=>"9",
                "type_child_id"=>"0",
                "type_name"=>"交流"
            ],
            [
                "type_parent_id"=>"10",
                "type_child_id"=>"0",
                "type_name"=>"歴史"
            ],
            [
                "type_parent_id"=>"11",
                "type_child_id"=>"0",
                "type_name"=>"生活・暮らし・健康・介護"
            ],
            [
                "type_parent_id"=>"12",
                "type_child_id"=>"0",
                "type_name"=>"エンタメ"
            ],
            [
                "type_parent_id"=>"13",
                "type_child_id"=>"0",
                "type_name"=>"チャリティー・エコ"
            ],
            [
                "type_parent_id"=>"14",
                "type_child_id"=>"0",
                "type_name"=>"ファッション"
            ],
            [
                "type_parent_id"=>"15",
                "type_child_id"=>"0",
                "type_name"=>"レジャー・自然"
            ],
            [
                "type_parent_id"=>"16",
                "type_child_id"=>"0",
                "type_name"=>"乗り物"
            ],
            [
                "type_parent_id"=>"17",
                "type_child_id"=>"0",
                "type_name"=>"寺・神社"
            ],
            [
                "type_parent_id"=>"18",
                "type_child_id"=>"0",
                "type_name"=>"芸術"
            ],
            [
                "type_parent_id"=>"19",
                "type_child_id"=>"0",
                "type_name"=>"物づくり"
            ],
            [
                "type_parent_id"=>"20",
                "type_child_id"=>"0",
                "type_name"=>"旅行"
            ],
            [
                "type_parent_id"=>"21",
                "type_child_id"=>"0",
                "type_name"=>"子供"
            ],
            [
                "type_parent_id"=>"22",
                "type_child_id"=>"0",
                "type_name"=>"季節"
            ]
        ]);
    }
}
